apiVersion: v1
kind: Pod
metadata:
  name: build-kaniko3
spec:
  containers:
  - name: kaniko-test
    image: gcr.io/kaniko-project/executor:debug
    args:
    - "--context=git@github.com:rajan563/kaniko-test.git"
    - "--git=branch=main"
    - "--destination=registry.digitalocean.com/springbootrajan/fiata-app"
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker
    env:
    - name: GIT_USERNAME
      value: rajan563
    - name: GIT_PASSWORD
      value: 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
  restartPolicy: Never
  volumes:
  - name: kaniko-secret
    secret:
      secretName: regcred
      items:
        - key: .dockerconfigjson
          path: config.json